baseURL: https://ghostsonatrampoline.net/
copyright: <!--Creative Commons License-->This site is licensed under a [Creative Commons Attribution-ShareAlike 4.0 International License](https://creativecommons.org/licenses/by-sa/4.0/).<!--/Creative Commons License-->
enableEmoji: true 
enableRobotsTXT: true
enableGitInfo: true
languageCode: en-us
theme: hugo-PolyRhythmic
title: Ghosts on a Trampoline
