baseURL: https://ghostsonatrampoline.net/
languageCode: en-us
theme: hugo-PolyRhythmic
enableEmoji: true 
title: Ghosts on a Trampoline
Description: GOAT description
copyright: <!--Creative Commons License-->This site is licensed under a [Creative Commons Attribution-ShareAlike 4.0 International License](https://creativecommons.org/licenses/by-sa/4.0/).<!--/Creative Commons License-->
enableRobotsTXT: true
enableGitInfo: true